# Generated by Django 3.2.11 on 2022-01-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
