# Generated by Django 3.2.11 on 2022-01-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0002_alter_post_title_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_image',
            new_name='files',
        ),
    ]
