# Generated by Django 3.2.11 on 2022-02-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0004_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='title',
            field=models.CharField(default=str, max_length=200),
        ),
    ]
