# Generated by Django 3.2.11 on 2022-02-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0005_biography_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biography',
            old_name='title',
            new_name='eng_name',
        ),
        migrations.AddField(
            model_name='biography',
            name='interest_first',
            field=models.CharField(default=str, max_length=50),
        ),
        migrations.AddField(
            model_name='biography',
            name='interest_se',
            field=models.CharField(default=str, max_length=50),
        ),
        migrations.AddField(
            model_name='biography',
            name='interest_third',
            field=models.CharField(default=str, max_length=50),
        ),
        migrations.AddField(
            model_name='biography',
            name='kr_name',
            field=models.CharField(default=str, max_length=20),
        ),
        migrations.AlterField(
            model_name='biography',
            name='images',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
