# Generated by Django 3.2.11 on 2022-02-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0007_auto_20220218_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='email',
            field=models.EmailField(default=str, max_length=254),
        ),
    ]
