# Generated by Django 3.2.11 on 2022-02-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0009_auto_20220225_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
    ]
