# Generated by Django 3.2.11 on 2022-02-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0010_remove_post_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
