# Generated by Django 3.2.11 on 2022-03-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0012_remove_post_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=str, max_length=300)),
                ('images', models.ImageField(upload_to='projects')),
                ('content', models.TextField()),
                ('institue', models.CharField(default=str, max_length=40)),
                ('project_strat_year', models.IntegerField(max_length=4)),
                ('project_strat_month', models.IntegerField(max_length=2)),
                ('project_strat_day', models.IntegerField(max_length=2)),
                ('project_end_year', models.IntegerField(max_length=4)),
                ('project_end_month', models.IntegerField(max_length=2)),
                ('project_end_day', models.IntegerField(max_length=2)),
            ],
        ),
    ]
