# Generated by Django 3.2.11 on 2022-03-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0013_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_end_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_end_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_end_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_strat_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_strat_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_strat_year',
            field=models.IntegerField(default=0),
        ),
    ]
