# Generated by Django 3.2.11 on 2022-03-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0014_auto_20220301_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_end_day',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_end_month',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_end_year',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_strat_day',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_strat_month',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_strat_year',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='프로젝트 종료일'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_strat_date',
            field=models.DateField(blank=True, null=True, verbose_name='프로젝트 시작일'),
        ),
    ]
